title: 大飴屋
email: oame@oameya.com
description: '大飴屋 Webサイト'
url: 'https://oameya.com'
twitter_username: o_ame
github_username: oame
google_analytics: 'UA-28919359-6'
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: '/blog/:year/:month/:day/:title'
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
sass:
  style: compressed
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - script
include:
  - _pages
