version: '3'
services:
  web:
    build: .
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --force_polling --baseurl '' --watch --drafts --unpublished
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
